-- MySQL Script generated by MySQL Workbench
-- 04/20/18 21:39:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema museu_bd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema museu_bd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `museu_bd` DEFAULT CHARACTER SET utf8 ;
USE `museu_bd` ;

-- -----------------------------------------------------
-- Table `museu_bd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museu_bd`.`usuario` (
  `id_usuario` INT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(80) NOT NULL,
  `senha_usuario` VARCHAR(15) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museu_bd`.`animais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museu_bd`.`animais` (
  `id_animais` INT NOT NULL AUTO_INCREMENT,
  `nome_animal` VARCHAR(45) NOT NULL,
  `nome_cientifico` VARCHAR(45) NOT NULL,
  `ordem_animal` VARCHAR(45) NOT NULL,
  `familia_animal` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `destribuicao` VARCHAR(255) NOT NULL,
  `descricao_geografica` VARCHAR(255) NOT NULL,
  `habito_alimentar` VARCHAR(255) NOT NULL,
  `pruducao` VARCHAR(200) NOT NULL,
  `periodo_vida` VARCHAR(200) NOT NULL,
  `habitat` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_animais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museu_bd`.`foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museu_bd`.`foto` (
  `id_foto` INT NULL AUTO_INCREMENT,
  `end_foto` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_foto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museu_bd`.`esposicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museu_bd`.`esposicao` (
  `idesposicao` INT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `locanizacao` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idesposicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museu_bd`.`animais_has_foto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museu_bd`.`animais_has_foto` (
  `animais_id_animais` INT NOT NULL,
  `foto_id_foto` INT NOT NULL,
  `esposicao_idesposicao` INT NOT NULL,
  PRIMARY KEY (`animais_id_animais`, `foto_id_foto`),
  INDEX `fk_animais_has_foto_foto1_idx` (`foto_id_foto` ASC),
  INDEX `fk_animais_has_foto_animais_idx` (`animais_id_animais` ASC),
  INDEX `fk_animais_has_foto_esposicao1_idx` (`esposicao_idesposicao` ASC),
  CONSTRAINT `fk_animais_has_foto_animais`
    FOREIGN KEY (`animais_id_animais`)
    REFERENCES `museu_bd`.`animais` (`id_animais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animais_has_foto_foto1`
    FOREIGN KEY (`foto_id_foto`)
    REFERENCES `museu_bd`.`foto` (`id_foto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animais_has_foto_esposicao1`
    FOREIGN KEY (`esposicao_idesposicao`)
    REFERENCES `museu_bd`.`esposicao` (`idesposicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `museu_bd`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `museu_bd`.`agendamento` (
  `id_agendamento` INT NOT NULL AUTO_INCREMENT,
  `instituicao` VARCHAR(60) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `telefone_secundario` VARCHAR(15) NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_visita` DATE NOT NULL,
  `hora_visita` DECIMAL(4) NOT NULL,
  `numero_visitantes` INT NOT NULL,
  `turno` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_agendamento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
